### PR TITLE
Upgrade HtmlToOpenXml to v3.1.0

### PR DESCRIPTION
**Pull request by onizet**
I'm the author of HtmlToOpenXml.dll package. I did a big refactoring work on this library to be more stable and parsing efficient. I have also fixed numerous bugs.

I'd really like to encourage you to update the dependency.

### CODE REVIEW

**Comment by mesquidar** [comment]
Hi @onizet first of all thank for your work on the library :)
I built a dev image with the new version 3.1.0 and we are testing it. 

Some of the users found some issues you can check it here:  https://github.com/CervantesSec/cervantes/issues/51#issuecomment-2313153962

**Comment by onizet** [comment]
Hello @mesquidar, thank you for your quick feedback.
I fixed that issue 3 weeks ago #onizet/html2openxml/issues/113 
Let me know if you are still facing that issue.

**Comment by mesquidar** [comment]
Hi @onizet thanks for your answer :)

Unfortunately the issue persists with the new version 3.1.0
Another thing that some user notice is there some issues with image align you can see the comment https://github.com/CervantesSec/cervantes/issues/51#issue-2465716197 

Thanks!

**Comment by onizet** [comment]
Hi Ruben, I have just release v3.1.1 which contain the bug fix mentioned in issue 51.
Table layout is correctly handled in v3+
The image alignment is currently not supported (`float: right`) but I'm working on it. That's not easy as OpenXml <> HTML and sometimes, this is just not possible to conform fully to Html5 standard.

**Comment by mesquidar** [comment]
Hi @onizet thanks for the update :)
I will take it a look at the new version

**Pull request merged**
